stages:
  extract:
    cmd: python src/data/extract_data.py
    deps:
      - src/data/extract_data.py
      - data/raw/dataset.zip
    outs:
      - data/interim:
          cache: false

  test_extracted_data:
    cmd: python src/tests/test_extract_data.py
    deps:
      - data/interim/keep grinding..csv
      - data/interim/Spotify's Most Played All-Time [Updated Weekly]  Most Streamed  Top
        Played  500Mil+.csv
      - src/tests/test_extract_data.py

  preprocessing:
    cmd: python src/features/preprocessing.py
    deps:
      - data/interim/keep grinding..csv
      - data/interim/Spotify's Most Played All-Time [Updated Weekly]  Most Streamed  Top
        Played  500Mil+.csv
      - src/features/preprocessing.py
    outs:
      - data/processed/trainSet.csv:
          cache: false
      - data/processed/testSet.csv:
          cache: false

  test_processed_data:
    cmd: python src/tests/test_preprocessed_data.py
    deps:
      - data/processed/trainSet.csv
      - data/processed/testSet.csv
      - src/tests/test_preprocessed_data.py

  clustering:
    cmd: python src/models/clustering.py
    deps:
      - data/processed/trainSet.csv
      - data/processed/testSet.csv
      - src/models/clustering.py
    outs:
      - data/output/clustertrainSet.csv:
          cache: false
      - data/output/clustertestSet.csv:
          cache: false
  recommending:
    cmd: python src/models/recommend.py
    deps:
      - data/output/clustertrainSet.csv
      - data/output/clustertestSet.csv
      - src/models/recommend.py
    outs:
      - data/output/recommendations.csv:
          cache: false
  metrics:
    cmd: python src/models/metrics.py
    deps:
      - data/interim/feedbackUser1.csv
      - data/interim/feedbackUser2.csv
      - data/output/recommendations.csv
      - src/models/metrics.py
