# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - stagingmusicexpress
run-name: Staging - Deploy to Azure Web App

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://stagingmusicexpress.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_335f76853fb641fcbf64ad6606f5ef86 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_13abbae63b874d7a8729f6f3b48e2637 }}

    - name: Set up DVC
      uses: iterative/setup-dvc@v1

    - name: Pull data with DVC
      env:
        GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
      run: |
        dvc pull

    - name: Build the Docker image
      run: docker build -t stagingmusicexpress.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_335f76853fb641fcbf64ad6606f5ef86 }}/stagingmusicexpress:${{ github.sha }} -f docker/Dockerfile . 
    
    - name: Push the Docker image to the Azure registry
      run: docker push stagingmusicexpress.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_335f76853fb641fcbf64ad6606f5ef86 }}/stagingmusicexpress:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'stagingmusicexpress'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3ba59260b4544bf29ff3adbf2bb2e3a9 }}
        images: 'stagingmusicexpress.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_335f76853fb641fcbf64ad6606f5ef86 }}/stagingmusicexpress:${{ github.sha }}'