# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - musicexpress
run-name: Production - Deploy to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://musicexpress.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_85d124765a2e4566bef9484990854434 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_6ed6760b112f4d809573e136d51e32d0 }}

    - name: Set up DVC
      uses: iterative/setup-dvc@v1

    - name: Pull data with DVC
      env:
        GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
      run: |
        dvc pull

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: musicexpress.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_85d124765a2e4566bef9484990854434 }}/musicexpress:${{ github.sha }}
        file: ./docker/Dockerfile
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'musicexpress'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b647c84f6b2b4c73a707a5b312f876ff }}
        images: 'musicexpress.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_85d124765a2e4566bef9484990854434 }}/musicexpress:${{ github.sha }}'