name: quality_assurance_workflow
run-name: Checking Pylint code quality after changes

on:
  push:
    paths:
      - "src/**"

jobs:
  pylint_qa:
    name: Pylint code quality assurance
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python >=3.11.5 <=3.11.6
        uses: actions/setup-python@v4
        with:
          python-version: ">=3.11.5 <=3.11.6"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt

      - name: Analyze code with pylint
        run: |
          pylint --fail-under=8 src/

  # flake8_qa:
  #   name: Flake8 code quality assurance
  #   runs-on: windows-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
  #     - name: Set up Python >=3.11.5 <=3.11.6
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: ">=3.11.5 <=3.11.6"
  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install -r ./requirements.txt
  #     - name: flake8 Lint
  #       uses: py-actions/flake8@v2
  #       with:
  #         path: "src/"
  #         ignore: "E226, E121, E123, E126, W504"
  #         exclude: "src/tests/test_deepchecks.py"
  #         max-line-length: "120"
